parserConfig:
  ssisFolder: C:\Users\Venki\OneDrive\python\GitHub\ssisParser\ssisSample

analysisModels:
  - name: package_data
    parent: ''
    columns:
      - name: packageName 
        path: '"DTS:Executable"."@DTS:DTSID"'
      - name: DTSID
        path: '"DTS:Executable"."@DTS:ObjectName"'
  - name: connections
    parent: ''
    columns:
      - name: packageName 
        path: '"DTS:Executable"."@DTS:ObjectName"'
      - name: DTSID
        path: '"DTS:Executable"."@DTS:DTSID"'
      - name: Connections 
        path: 'unnest("DTS:Executable"."DTS:ConnectionManagers"."DTS:ConnectionManager")'
     
     
